# Etapa de construcción
FROM node:20-alpine AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de configuración de dependencias
COPY package.json ./

# Instalar dependencias de desarrollo
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Construir la aplicación
RUN npm run build


# Etapa de producción
FROM node:20-alpine AS production

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de configuración de dependencias
COPY package.json ./

# Instalar solo las dependencias de producción
RUN npm install 

# Copiar los archivos construidos desde la etapa de construcción
COPY --from=build /app/dist ./dist

# Exponer el puerto en el que la aplicación se ejecuta
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["node", "dist/main.js"]
