name: 🚀 NestJS Backend Deployment Pipeline

on:
  push:
    branches: ['main-backend']
  pull_request:
    branches: ['main-backend']

concurrency:
  group: ci-${{github.ref}}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: npm ci --legacy-peer-deps
        working-directory: Proyecto/backend

      - run: npm run build
        working-directory: Proyecto/backend
